# Generated by Django 2.1.5 on 2019-02-11 08:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.TextField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('telephone', models.TextField(max_length=255)),
                ('mobile', models.TextField(max_length=25)),
                ('address', models.TextField(max_length=255)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('update', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('posted_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Mentee')),
            ],
        ),
    ]
