# Generated by Django 2.1.5 on 2019-02-11 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kebun_Binatang', '0002_auto_20190211_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nomor_telepon',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='nomor_telepon',
            field=models.CharField(max_length=255),
        ),
    ]
