# Generated by Django 2.1.5 on 2019-02-11 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=255)),
                ('banyak_soal', models.PositiveIntegerField()),
                ('bobot_nilai', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('jabatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Live_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=255)),
                ('banyak_soal', models.CharField(max_length=255)),
                ('bobot_nilai', models.PositiveIntegerField()),
                ('tanggal_pelaksanaan', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Mata_pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=255)),
                ('jadwal_dimulai', models.DateTimeField(default=django.utils.timezone.now)),
                ('jadwal_berakhir', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('nomor_absen', models.PositiveIntegerField()),
                ('nilai_ratarata', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('mata_pelajaran', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran')),
            ],
        ),
        migrations.AddField(
            model_name='live_code',
            name='mata_pelajaran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='mata_pelajaran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran'),
        ),
    ]
