# Generated by Django 2.1.5 on 2019-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nomor_telepon', models.PositiveIntegerField()),
                ('alamat', models.TextField(max_length=255)),
                ('keluhan', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dokter',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='dokter',
            name='keluhan',
        ),
        migrations.AddField(
            model_name='dokter',
            name='bidang',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.CharField(max_length=255),
        ),
    ]
